{% set name = "pygraft" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygraft-{{ version }}.tar.gz
  sha256: 2912b26d59404e64448c814ee0a09ff5b34f4454cf573a51c7890514f9311240

build:
  entry_points:
    - pygraft = pygraft.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip

    # Need to constrain setuptools since package is setup in a legacy format
    - setuptools <69
  run:
    - python >={{ python_min }}
    - numpy >=1.24.0
    - matplotlib-base >=3.7.0
    - owlready2 >=0.41
    - rdflib >=6.2.0
    - pyyaml
    - tabulate
    - ascii-art
    - tqdm

test:
  imports:
    - pygraft
  commands:
    - pip check
    - pygraft --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nicolas-hbt
  summary: Configurable generation of schemas and knowledge graphs at your fingertips
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
